# Generated by Django 4.1.5 on 2023-02-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-13 03:26:22", null=True
            ),
        ),
    ]
