# Generated by Django 4.1.5 on 2023-01-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=500)),
                ("version", models.IntegerField()),
                ("periods", models.ManyToManyField(to="beacon.period")),
            ],
        ),
    ]
