# Generated by Django 4.1.5 on 2023-01-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beacon.period",
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-01-20 20:14:08", null=True
            ),
        ),
    ]
