# Generated by Django 4.1.5 on 2023-01-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="attribute", name="scenario",),
    ]
