# Generated by Django 4.1.5 on 2023-01-14 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="acc_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="collection",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beacon.currency",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="data_type",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="beacon.currency"
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="avg_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="begin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="end_spot_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beacon.country",
            ),
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adj_type", models.CharField(max_length=100)),
                (
                    "adj_collection",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("adj_class", models.CharField(blank=True, max_length=100, null=True)),
                ("adj_percentage", models.FloatField(blank=True, null=True)),
                ("adj_amount", models.FloatField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="beacon.account"
                    ),
                ),
            ],
        ),
    ]
