# Generated by Django 4.1.5 on 2023-01-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_name", models.CharField(max_length=100)),
                ("attribute_value", models.CharField(max_length=50)),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.RemoveField(model_name="scenario", name="scn_id",),
    ]
