# Generated by Django 4.1.5 on 2023-02-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0002_alter_scenario_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-15 03:53:50", null=True
            ),
        ),
        migrations.CreateModel(
            name="DefaultAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("attribute_name", models.CharField(max_length=100)),
                ("attribute_value", models.CharField(max_length=50)),
                ("scenario", models.CharField(max_length=100)),
                ("begin_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={"unique_together": {("entity_type", "attribute_name")},},
        ),
    ]
