# Generated by Django 4.1.5 on 2023-01-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0002_remove_attribute_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity", name="name", field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="entity", unique_together={("name", "scenario")},
        ),
    ]
