# Generated by Django 4.1.5 on 2023-01-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0002_alter_account_acc_class_alter_account_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="scenario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beacon.scenario",
            ),
        ),
    ]
