# Generated by Django 4.1.5 on 2023-01-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0002_attribute_remove_scenario_scn_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
