# Generated by Django 4.1.5 on 2023-02-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0003_alter_scenario_modify_date_defaultattribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-15 04:00:17", null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="defaultattribute",
            unique_together={("entity_type", "attribute_value", "attribute_name")},
        ),
    ]
