# Generated by Django 4.1.5 on 2023-01-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0003_alter_scenario_description_entity"),
    ]

    operations = [
        migrations.RemoveField(model_name="entity", name="period",),
    ]
