# Generated by Django 4.1.5 on 2023-01-14 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0004_alter_attribute_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="scenario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beacon.scenario",
            ),
        ),
    ]
