# Generated by Django 4.1.5 on 2023-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0004_alter_scenario_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-01-28 20:43:24", null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("account_name", "scenario", "entity", "collection")},
        ),
    ]
