# Generated by Django 4.1.5 on 2023-02-15 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0004_alter_scenario_modify_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="beacon.entity",
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-15 04:24:48", null=True
            ),
        ),
    ]
