# Generated by Django 4.1.5 on 2023-01-14 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0005_account_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="beacon.scenario"
            ),
        ),
    ]
