# Generated by Django 4.1.5 on 2023-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0006_alter_scenario_modify_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="period", unique_together=set(),),
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-04 17:45:10", null=True
            ),
        ),
    ]
