# Generated by Django 4.1.5 on 2023-01-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0007_alter_scenario_scn_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="account", unique_together={("account_name", "scenario")},
        ),
    ]
