# Generated by Django 4.1.5 on 2023-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0007_alter_period_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-04 19:19:29", null=True
            ),
        ),
    ]
