# Generated by Django 4.1.5 on 2023-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0009_alter_scenario_modify_date_log"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log", old_name="exception", new_name="message",
        ),
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-04 20:16:18", null=True
            ),
        ),
    ]
