# Generated by Django 4.1.5 on 2023-02-05 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0012_importlog_scenario_alter_scenario_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="beacon.scenario"
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-05 02:17:21", null=True
            ),
        ),
    ]
