# Generated by Django 4.1.5 on 2023-02-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0013_alter_importlog_scenario_alter_scenario_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importlog",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-05 02:18:14", null=True
            ),
        ),
    ]
