# Generated by Django 4.1.5 on 2023-02-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beacon", "0015_alter_scenario_modify_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="child",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="beacon.entity",
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="modify_date",
            field=models.DateTimeField(
                blank=True, default="2023-02-05 02:59:52", null=True
            ),
        ),
    ]
